development:
  adapter: postgresql
  encoding: unicode
  database: dashit_development
  username: dashit
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: dashit_production
  username: dashit
  pool: 5
